/**
 * FILE: units.js
 *
 * Units management modal (SQLite-backed via /api/units/* endpoints).
 *
 * Bridge name: window.AppUnits
 */
(function () {
    'use strict';

    const LEVELS = [
        { value: 0, label: 'Army' },
        { value: 1, label: 'Land Force' },
        { value: 2, label: 'Brigade' },
        { value: 3, label: 'Battalion' },
        { value: 4, label: 'Company' },
    ];

    function qs(sel) { return document.querySelector(sel); }
    function byId(id) { return document.getElementById(id); }

    function escapeHtml(s) {
        return String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]));
    }

    async function apiJson(url, opts = {}) {
        const res = await fetch(url, {
            credentials: 'include',
            headers: { 'Content-Type': 'application/json' },
            ...opts,
        });
        const txt = await res.text();
        let json = null;
        try { json = txt ? JSON.parse(txt) : null; } catch {}
        if (!res.ok) {
            const msg = json && json.error ? json.error : (txt || (res.status + ' ' + res.statusText));
            const err = new Error(msg);
            err.status = res.status;
            err.payload = json;
            throw err;
        }
        return json;
    }

    function flattenTree(roots) {
        const out = [];
        (function walk(nodes, depth) {
            for (const n of nodes || []) {
                out.push({ ...n, _depth: depth });
                if (n.children && n.children.length) walk(n.children, depth + 1);
            }
        })(roots || [], 0);
        return out;
    }

    function init() {
        const modal = byId('units-modal');
        const backdrop = byId('units-modal-backdrop');
        const closeBtn = byId('units-modal-close');
        const treeEl = byId('units-tree');
        const searchInput = byId('units-search-input');
        const refreshBtn = byId('units-refresh-btn');
        const includeDeletedCb = byId('units-include-deleted');

        const selectedNameEl = byId('units-selected-name');
        const selectedMetaEl = byId('units-selected-meta');
        const errorEl = byId('units-error');

        const codeEl = byId('units-code');
        const nameEl = byId('units-name');
        const levelEl = byId('units-level');
        const parentEl = byId('units-parent');
        const sidcEl = byId('units-sidc');
        const typeEl = byId('units-type');

        const createBtn = byId('units-create-btn');
        const saveBtn = byId('units-save-btn');
        const moveBtn = byId('units-move-btn');
        const deleteBtn = byId('units-delete-btn');
        const restoreBtn = byId('units-restore-btn');

        const railBtn = document.querySelector('.tool-rail-btn[data-tool="units"]');

        if (!modal || !treeEl || !railBtn) return;

        let state = {
            roots: [],
            units: [],
            selectedId: null,
        };

        let lastAutoGeneratedCode = '';
        let codeCheckTimer = null;
        let codeAvailable = true;

        function setButtonsEnabled() {
            const hasCode = !!(codeEl.value || '').trim();
            const hasName = !!(nameEl.value || '').trim();
            const ok = hasName && hasCode && codeAvailable;
            if (createBtn) createBtn.disabled = !ok;
            if (saveBtn) saveBtn.disabled = !ok || !getSelected();
        }

        function showError(msg) {
            if (!errorEl) return;
            errorEl.textContent = msg ? String(msg) : '';
            errorEl.classList.toggle('hidden', !msg);
        }

        function open() {
            modal.classList.remove('hidden');
            modal.setAttribute('aria-hidden', 'false');
            showError('');
            refresh();
        }

        function close() {
            modal.classList.add('hidden');
            modal.setAttribute('aria-hidden', 'true');
            showError('');
        }

        function getSelected() {
            return state.units.find(u => u.id === state.selectedId) || null;
        }

        function setSelected(id) {
            state.selectedId = id;
            const u = getSelected();
            if (!u) {
                selectedNameEl.textContent = '—';
                selectedMetaEl.textContent = '';
                codeEl.value = '';
                nameEl.value = '';
                sidcEl.value = '';
                typeEl.value = '';
                return;
            }
            selectedNameEl.textContent = u.name || '—';
            selectedMetaEl.textContent = `${u.code || ''}${u.level != null ? ' • L' + u.level : ''}${u.deleted_at ? ' • deleted' : ''}`;
            codeEl.value = u.code || '';
            nameEl.value = u.name || '';
            levelEl.value = String(u.level ?? 0);
            parentEl.value = u.parent_id || '';
            sidcEl.value = u.sidc || '';
            typeEl.value = u.unit_type || '';
        }

        function prefixForLevel(level) {
            switch (Number(level)) {
                case 0: return 'ARMY';
                case 1: return 'LF';
                case 2: return 'BDE';
                case 3: return 'BN';
                case 4: return 'CO';
                default: return 'U';
            }
        }

        function randSuffix() {
            const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
            let s = '';
            for (let i = 0; i < 4; i++) s += chars[Math.floor(Math.random() * chars.length)];
            return s;
        }

        function autoGenerateCodeIfEmpty() {
            const current = (codeEl.value || '').trim();
            if (current) return;
            const lvl = Number.parseInt(levelEl.value, 10);
            const suggestion = `${prefixForLevel(lvl)}-${randSuffix()}`;
            lastAutoGeneratedCode = suggestion;
            codeEl.value = suggestion;
        }

        async function checkCodeAvailability() {
            const code = (codeEl.value || '').trim();
            if (!code) {
                codeAvailable = false;
                setButtonsEnabled();
                return;
            }
            const sel = getSelected();
            const excludeId = sel ? sel.id : '';
            try {
                const data = await apiJson(`/api/units/code-check?code=${encodeURIComponent(code)}&excludeId=${encodeURIComponent(excludeId)}`);
                codeAvailable = !!data.available;
                if (!codeAvailable) {
                    showError('Code already exists. Choose a different code.');
                } else if (String(showError) && errorEl && errorEl.textContent && errorEl.textContent.includes('Code already exists')) {
                    showError('');
                }
            } catch (e) {
                // If check endpoint fails, don't block the user; server will still enforce uniqueness.
                codeAvailable = true;
            }
            setButtonsEnabled();
        }

        function renderParentOptions() {
            const includeDeleted = !!includeDeletedCb?.checked;
            const units = includeDeleted ? state.units : state.units.filter(u => !u.deleted_at);
            const selected = getSelected();

            const opt = [];
            opt.push(`<option value="">—</option>`);
            for (const u of units) {
                // only allow parent levels 0..3
                if (u.level == null || u.level >= 4) continue;
                // cannot parent to itself
                if (selected && u.id === selected.id) continue;
                opt.push(`<option value="${escapeHtml(u.id)}">${escapeHtml(u.code)} — ${escapeHtml(u.name)} (L${u.level})</option>`);
            }
            parentEl.innerHTML = opt.join('');
        }

        function renderTree() {
            const flat = flattenTree(state.roots);
            const selectedId = state.selectedId;
            const html = flat.map(n => {
                const pad = 8 + n._depth * 14;
                const isSel = n.id === selectedId;
                const deleted = !!n.deletedAt || !!n.deleted_at;
                const label = `${escapeHtml(n.code)} — ${escapeHtml(n.name)}`;
                return `
                  <div class="units-tree-row ${isSel ? 'active' : ''} ${deleted ? 'deleted' : ''}" data-id="${escapeHtml(n.id)}" style="padding-inline-start:${pad}px">
                    <span class="units-tree-level">L${escapeHtml(n.level)}</span>
                    <span class="units-tree-label">${label}</span>
                  </div>
                `;
            }).join('');
            treeEl.innerHTML = html || `<div class="units-tree-empty">No units</div>`;
        }

        async function refresh() {
            showError('');
            const includeDeleted = !!includeDeletedCb?.checked;
            try {
                const data = await apiJson(`/api/units/tree?includeDeleted=${includeDeleted ? 1 : 0}`);
                state.roots = data.roots || [];
                state.units = data.units || [];
                renderParentOptions();
                renderTree();
                // keep selection if possible
                if (state.selectedId && !state.units.find(u => u.id === state.selectedId)) {
                    state.selectedId = null;
                }
                setSelected(state.selectedId);
                setButtonsEnabled();
            } catch (e) {
                showError(e.message || 'Failed to load units');
            }
        }

        async function doSearch() {
            const q = (searchInput.value || '').trim();
            if (!q) return refresh();
            const includeDeleted = !!includeDeletedCb?.checked;
            showError('');
            try {
                const data = await apiJson(`/api/units/search?q=${encodeURIComponent(q)}&includeDeleted=${includeDeleted ? 1 : 0}`);
                // Render as a flat list in the tree area
                state.roots = [];
                state.units = (data.results || []);
                renderParentOptions();
                treeEl.innerHTML = (data.results || []).map(u => {
                    const isSel = u.id === state.selectedId;
                    const deleted = !!u.deleted_at;
                    return `
                      <div class="units-tree-row ${isSel ? 'active' : ''} ${deleted ? 'deleted' : ''}" data-id="${escapeHtml(u.id)}" style="padding-inline-start:8px">
                        <span class="units-tree-level">L${escapeHtml(u.level)}</span>
                        <span class="units-tree-label">${escapeHtml(u.code)} — ${escapeHtml(u.name)}</span>
                      </div>
                    `;
                }).join('') || `<div class="units-tree-empty">No results</div>`;
            } catch (e) {
                showError(e.message || 'Search failed');
            }
        }

        async function createUnit() {
            showError('');
            await checkCodeAvailability();
            if (!codeAvailable) return;
            const payload = {
                code: (codeEl.value || '').trim(),
                name: (nameEl.value || '').trim(),
                level: Number.parseInt(levelEl.value, 10),
                parentId: (parentEl.value || '').trim() || null,
                sidc: (sidcEl.value || '').trim() || null,
                unitType: (typeEl.value || '').trim() || null,
            };
            try {
                const row = await apiJson('/api/units', { method: 'POST', body: JSON.stringify(payload) });
                state.selectedId = row.id;
                await refresh();
            } catch (e) {
                showError(e.message || 'Create failed');
            }
        }

        async function saveUnit() {
            const u = getSelected();
            if (!u) return;
            showError('');
            await checkCodeAvailability();
            if (!codeAvailable) return;
            const payload = {
                code: (codeEl.value || '').trim(),
                name: (nameEl.value || '').trim(),
                level: Number.parseInt(levelEl.value, 10),
                sidc: (sidcEl.value || '').trim() || null,
                unitType: (typeEl.value || '').trim() || null,
            };
            try {
                const row = await apiJson(`/api/units/${encodeURIComponent(u.id)}`, { method: 'PATCH', body: JSON.stringify(payload) });
                state.selectedId = row.id;
                await refresh();
            } catch (e) {
                showError(e.message || 'Save failed');
            }
        }

        async function moveUnit() {
            const u = getSelected();
            if (!u) return;
            showError('');
            const newParentId = (parentEl.value || '').trim();
            if (!newParentId) { showError('new parent is required'); return; }
            try {
                const row = await apiJson(`/api/units/${encodeURIComponent(u.id)}/move`, { method: 'POST', body: JSON.stringify({ newParentId }) });
                state.selectedId = row.id;
                await refresh();
            } catch (e) {
                showError(e.message || 'Move failed');
            }
        }

        async function deleteUnit() {
            const u = getSelected();
            if (!u) return;
            showError('');
            try {
                await apiJson(`/api/units/${encodeURIComponent(u.id)}/delete`, { method: 'POST', body: '{}' });
                await refresh();
            } catch (e) {
                showError(e.message || 'Delete failed');
            }
        }

        async function restoreUnit() {
            const u = getSelected();
            if (!u) return;
            showError('');
            try {
                await apiJson(`/api/units/${encodeURIComponent(u.id)}/restore`, { method: 'POST', body: '{}' });
                await refresh();
            } catch (e) {
                showError(e.message || 'Restore failed');
            }
        }

        // Events
        railBtn.addEventListener('click', (e) => {
            e.preventDefault();
            open();
        });
        backdrop?.addEventListener('click', close);
        closeBtn?.addEventListener('click', close);
        document.addEventListener('keydown', (e) => {
            if (e.key === 'Escape' && !modal.classList.contains('hidden')) close();
        });
        refreshBtn?.addEventListener('click', refresh);
        includeDeletedCb?.addEventListener('change', refresh);

        treeEl.addEventListener('click', (e) => {
            const row = e.target && e.target.closest ? e.target.closest('.units-tree-row') : null;
            const id = row ? row.getAttribute('data-id') : null;
            if (id) setSelected(id);
        });

        let searchTimer = null;
        searchInput?.addEventListener('input', () => {
            if (searchTimer) clearTimeout(searchTimer);
            searchTimer = setTimeout(doSearch, 250);
        });

        createBtn?.addEventListener('click', createUnit);
        saveBtn?.addEventListener('click', saveUnit);
        moveBtn?.addEventListener('click', moveUnit);
        deleteBtn?.addEventListener('click', deleteUnit);
        restoreBtn?.addEventListener('click', restoreUnit);

        // Populate level select defensively (in case HTML changes)
        if (levelEl && levelEl.options && levelEl.options.length === 0) {
            levelEl.innerHTML = LEVELS.map(l => `<option value="${l.value}">${escapeHtml(l.label)}</option>`).join('');
        }

        // Auto-generate code when level/parent changes (only if code is empty)
        levelEl?.addEventListener('change', () => {
            autoGenerateCodeIfEmpty();
            checkCodeAvailability();
        });
        parentEl?.addEventListener('change', () => {
            autoGenerateCodeIfEmpty();
            checkCodeAvailability();
        });

        // Code uniqueness checks on edit
        codeEl?.addEventListener('input', () => {
            showError('');
            codeAvailable = true;
            setButtonsEnabled();
            if (codeCheckTimer) clearTimeout(codeCheckTimer);
            codeCheckTimer = setTimeout(checkCodeAvailability, 300);
        });
        codeEl?.addEventListener('blur', () => {
            if (codeCheckTimer) clearTimeout(codeCheckTimer);
            checkCodeAvailability();
        });
        nameEl?.addEventListener('input', setButtonsEnabled);

        // Initial state
        autoGenerateCodeIfEmpty();
        setButtonsEnabled();
    }

    window.AppUnits = { init };
})();

